version: '3.8'
services:
  django:
    build: ./django
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - 8000
    volumes:
      - ./src:/code
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./django
    command: celery -A config worker --loglevel=info
    volumes:
      - ./src:/code
    depends_on:
      - redis
      - django

  celery_beat:
    build: ./django
    command: celery -A config beat --loglevel=info
    volumes:
      - ./src:/code
    depends_on:
      - redis
      - django

  db:
    image: postgres:15.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=iniad
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb

  redis:
    image: redis
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src/collected_static:/static
    depends_on:
      - django
      - redis

volumes:
  postgres-data:
