services:
  - type: web
    name: django-web
    env: docker
    plan: free
    dockerfilePath: ./django/Dockerfile
    dockerContext: .  # ルートディレクトリをビルドコンテキストに変更
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
    autoDeploy: true
