# Generated by Django 5.1.1 on 2024-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepadvice',
            name='topic_question',
            field=models.TextField(null=True),
        ),
    ]
