# Generated by Django 5.1.1 on 2024-10-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_sleepadvice_topic_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_time', models.TimeField()),
                ('mission', models.TextField()),
            ],
        ),
    ]
