# Generated by Django 5.1.2 on 2024-10-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
