# Generated by Django 5.1.4 on 2024-12-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_missionoption_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepadvice',
            name='mission_achievement',
            field=models.IntegerField(choices=[(1, '全くできなかった'), (2, 'あまりできなかった'), (3, '半分くらいできた'), (4, 'ほぼできた'), (5, '完全にできた')], null=True),
        ),
        migrations.AddField(
            model_name='sleepadvice',
            name='sleep_quality',
            field=models.IntegerField(choices=[(1, '目覚めが悪かった'), (2, 'あまり良くなかった'), (3, '普通'), (4, '良かった'), (5, 'すっきり目覚めた')], null=True),
        ),
    ]
