# Generated by Django 5.1.4 on 2024-12-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_sleepadvice_mission_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepadvice',
            name='sleep_duration',
            field=models.DurationField(null=True),
        ),
    ]
