# Generated by Django 5.1.3 on 2024-12-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_missiongenerate_missiongeneratevote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missiongeneratevote',
            name='mission_option',
        ),
    ]
