# Generated by Django 5.1.3 on 2025-01-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_missiongeneratevote_mission_option'),
        ('chat', '0009_sleepadvice_sleep_duration'),
    ]

    operations = [
    ]
