# Generated by Django 5.1.3 on 2025-01-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_vote_deadline_alter_groupmember_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_join_closed',
            field=models.BooleanField(default=False),
        ),
    ]
