# Generated by Django 5.1.4 on 2025-01-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_vote_deadline_alter_groupmember_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='init_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
