# Generated by Django 5.1.3 on 2025-01-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_init_message_sent'),
        ('groups', '0005_group_is_join_closed'),
    ]

    operations = [
    ]
